// Define the navigation data object
export const navData = {
  Home: {
    link: "/",
    text: "Home",
  },
  Games: [
    { text: "Action", link: "/action" },
    { text: "Adventure", link: "/adventure" },
    { text: "Arcade", link: "/arcade" },
    { text: "Board Game", link: "/board-game" },
    { text: "Card", link: "/card" },
    { text: "Casual", link: "/casual" },
    { text: "Music", link: "/music" },
    { text: "Puzzle", link: "/puzzle" },
    { text: "Racing", link: "/racing" },
    { text: "Role Playing", link: "/role-playing" },
    { text: "Simulation", link: "/simulation" },
    { text: "Sport", link: "/sport" },
    { text: "Strategy", link: "/strategy" },
    { text: "Survival", link: "/survival" },
  ],
  Apps: [
    { text: "Art & Design", link: "/art-&-design" },
    { text: "Books & Reference", link: "/books-&-references" },
    { text: "Browser", link: "/browser" },
    { text: "Business", link: "/board-game" },
    { text: "Card", link: "/card" },
    { text: "Casual", link: "/casual" },
    { text: "Music", link: "/music" },
    { text: "Puzzle", link: "/puzzle" },
    { text: "Racing", link: "/racing" },
    { text: "Role Playing", link: "/role-playing" },
    { text: "Simulation", link: "/simulation" },
    { text: "Sport", link: "/sport" },
    { text: "Strategy", link: "/strategy" },
    { text: "Survival", link: "/survival" },
  ],
  Community: {
    link: "/community",
    text: "Community",
  },
};
